Repository LYOfficial/BBSPK, pull requests merged in 2024-11, with the labels that each got.

#364 两个修改
  res/data/forums.js
Labels: 数据更新

#365 合并 dev 分支
  res/data/forums.js
Labels: 合并分支

#370 Dev
  res/data/forums.js
Labels: 合并分支

#371 Minecraft Fans 论坛 closed
  res/data/forums.js
Labels: 合并分支

#372 新增方块星球
  res/data/forums.js
Labels: 数据新增, 合并分支

#373 删除MineSpeak
  res/data/forums.js
Labels: 数据修正

#374 合并 dev 分支
  res/data/forums.js
Labels: 合并分支

#375 修正MCBBS维护开始日期
  res/class/DOMConstructor.js
  res/data/forums.js
Labels: 数据修正
