Repository LYOfficial/BBSPK, pull requests merged in 2024-05, with the labels that each got.

#265 增加史莱姆社区
  res/data/forums.js
Labels: 数据新增

#266 合并 Dev 分支
  res/data/forums.js
Labels: 合并分支

#267 更新数个网站状态
  res/data/forums.js
Labels: 数据更新

#268 合并 Dev 分支
  res/data/forums.js
Labels: 合并分支

#269 细节优化更改
  res/data/forums.js
Labels: 数据更新

#270 合并 Dev 分支
  res/data/forums.js
Labels: 合并分支

#271 合并 Dev 分支
  .github/workflows/ping.yml
Labels: 合并分支

#272 更新工作流
  .github/workflows/ping.yml
Labels: 数据更新, 合并分支

#276 修改论坛信息
  .github/workflows/ping.yml
  res/data/forums.js
Labels: 数据更新, 数据新增

#278 add imc
  res/data/forums.js
Labels: 数据新增

#279 合并 Dev 分支
  .github/workflows/ping.yml
  res/data/forums.js
Labels: 合并分支

#280 合并 Dev 分支
  res/data/forums.js
Labels: 数据更新, 合并分支

#281 更新时间
  res/data/forums.js
Labels: 数据更新

#282 更新状态
  res/data/forums.js
Labels: 数据更新, 合并分支

#285 添加一个表演赛选手
  res/data/forums.js
Labels: 数据新增

#286 更新
  res/data/forums.js
Labels: 数据更新

#287 合并 Dev 分支
  res/data/forums.js
Labels: 合并分支

#288 Update forums.js
  res/data/forums.js
Labels: 数据新增

#290 合并 Dev 分支
  res/data/forums.js
Labels: 合并分支

#292 撤回更改
  res/data/forums.js
Labels: 合并分支
