Repository LYOfficial/BBSPK, pull requests merged in 2024-08, with the labels that each got.

#322 新增金苹果论坛
  res/data/forums.js
Labels: 数据新增, 合并分支

#323 像素工坊 up
  res/data/forums.js
Labels: 数据更新, 合并分支

#324 SodaMC up, NWBBS close
  res/data/forums.js
Labels: 数据更新, 合并分支

#326 Update forums.js
  res/data/forums.js
Labels: 数据更新

#327 合并 Dev 分支
  res/data/forums.js
Labels: 合并分支

#328 Update forums.js
  res/data/forums.js
Labels: 数据新增

#329 石头论坛
  res/data/forums.js
Labels: 数据新增

#330 查活，新增论坛，更新
  res/data/forums.js
Labels: 数据更新, 数据新增

#331 合并 Dev 分支
  res/data/forums.js
Labels: 合并分支

#332 新增 CraftBBS
  res/data/forums.js
Labels: 数据新增, 合并分支

#333 拉黑 app.tc：免费主机
  res/data/forums.js
  res/data/url-black-list.js
Labels: 数据修正, 合并分支

#334 stone bbs 故障
  res/data/forums.js
Labels: 数据更新, 合并分支

#335 修改HiMCBBS建立日期
  res/data/forums.js
Labels: 数据更新

#336 合并 Dev 更改
  res/data/forums.js
Labels: 合并分支

#339 更新状态
  res/data/forums.js
Labels: 数据更新, 合并分支

#341 黑名单新增 00.uy
  res/data/url-black-list.js
Labels: 数据新增, 合并分支

#344 合并 Dev 分支
  res/data/forums.js
Labels: 合并分支
