Repository LYOfficial/BBSPK, pull requests merged in 2024-09, with the labels that each got.

#345 大更新
  res/data/forums.js
Labels: 数据更新, 数据新增

#347 合并 dev 分支
  res/data/forums.js
Labels: 合并分支

#348 移除 QuickShaders：这不是综合性论坛
  res/data/forums.js
Labels: 数据修正, 合并分支

#350 更名“KunMC我的世界论坛”名为“MCNeko我的世界论坛”
  res/data/forums.js
Labels: 数据更新

#351 合并 dev 分支
  res/data/forums.js
Labels: 合并分支

#352 更新论坛状态
  res/data/forums.js
Labels: 数据更新

#353 合并 dev 分支
  res/data/forums.js
Labels: 合并分支

#354 fix
  res/data/forums.js
Labels: 合并分支
